name: very_supply_api_client
repository: https://github.com/vassilyvv/very-supply-api-client
description: The library contains all the necessary methods to interact with very.supply API.
version: 0.0.14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  js: ^0.6.7
  collection: ^1.17.1